# Generated by Django 4.2.2 on 2023-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
    ]
