# Generated by Django 4.2.2 on 2023-06-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmiosfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-number',), 'verbose_name': 'Öğrenciler', 'verbose_name_plural': 'Öğrenci'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='fist_name',
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
